require("peinan.native.options")
require("peinan.native.matchparen")
require("peinan.native.terminal")
require("peinan.native.statuscolumn")
require("peinan.native.winbar")
require("peinan.native.lsp")
require("peinan.native.notify")
